version: '3'
services:
  app:
    image: node:10
    container_name: linux-dungeon_app
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash
    tty: true
    links:
      - db
      - ssh
    environment:
      - DATABASE_HOST=db
      - SSH_HOST=ssh
  db:
    image: mysql:5.6
    container_name: linux-dungeon_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/sqls:/docker-entrypoint-initdb.d
      - ./db/datas:/db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=linuxdungeon"
  ssh:
    build: ./ssh
    container_name: linux-dungeon_ssh
    ports:
      - "22:22"
